### ISSUE TITLE
Bump gem version

### ISSUE THREAD

**Issue by jason-o-matic** [sconover/wrong#39]
https://github.com/sconover/wrong/pull/30 is needed to work with cucumber.  It's merged into master, but a new version hasn't been released.

**Comment by alexch** [comment]
This causes a test to fail... looking into it now.

**Comment by alexch** [comment]
There's a bug in diff-lcs, fixed by https://github.com/halostatue/diff-lcs/commit/26e2dbddaa2ca78944bf4499de6766858a161b1d which hasn't been released yet, around diffing arrays of arrays.

**Comment by jason-o-matic** [comment]
Thanks for looking into it.  I posted an issue for diff-lcs (https://github.com/halostatue/diff-lcs/issues/24) so hopefully you'll be able to update soon.

**Comment by jason-o-matic** [comment]
@halostatue helped us out by releasing a new diff-lcs version.  Anything else necessary?

**Comment by alexch** [comment]
Release 0.7.1, 71ae609

Thanks for keeping on top of this... I hadn't noticed the new diff-lcs version.

**Comment by mpasternacki** [comment]
The 0.7.1 release commit linked above (71ae609b2b71a0bd8e9a2f93f0fba96b7fca68c2) and its parent (bc889159550c6b89c8bb66475025f82be71f8ae3) doesn't seem to be on any branch; I can browse them from the direct link above, but can't seem to find them starting at github's repository page, and when I `git clone https://github.com/sconover/wrong.git`, I don't receive any of these commits. Is this intentional?

**Comment by alexch** [comment]
Not intentional. Let me check my repos later. They may be in my personal fork github.com/alexch/wrong

**Comment by mpasternacki** [comment]
These commits are included in tag v0.7.1 in alexch/wrong (but in none of the branches in that fork either): https://github.com/alexch/wrong/compare/v0.7.1
